import React, { useEffect } from 'react';
import { X, Printer, Download, FileText, CheckCircle2, User, Phone, MapPin, Calendar, CreditCard, ShieldCheck, MessageSquare } from 'lucide-react';
import { formatRupees, formatNumberIN } from '../utils/currency';
import { printReceiptHtml } from '../utils/print';
import { sendInvoiceWhatsApp } from '../services/whatsappService';
import { useAlert } from '../context/AlertContext';
import WhatsAppPhoneBadge from './WhatsAppPhoneBadge';

export default function AdminInvoiceModal({ invoice, onClose, shopDetails }) {
  const { toast } = useAlert();

  useEffect(() => {
    // Close on Escape key press
    const handleKeyDown = (e) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [onClose]);

  if (!invoice) return null;

  const handlePrint = (e) => {
    if (e) {
      e.preventDefault();
      e.stopPropagation();
    }
    const receiptElem = document.getElementById('admin-printable-receipt');
    if (receiptElem) {
      printReceiptHtml(receiptElem.outerHTML);
    } else {
      window.print();
    }
  };

  const handleSendWhatsApp = (e) => {
    if (e) {
      e.preventDefault();
      e.stopPropagation();
    }
    sendInvoiceWhatsApp(invoice, toast);
  };

  const handleDownloadPDF = (e) => {
    if (e) {
      e.preventDefault();
      e.stopPropagation();
    }
    // Triggers standard print-to-PDF print dialog
    handlePrint(e);
  };

  const custName = invoice.customer?.name || invoice.customerName || 'Walk-in Customer';
  const custPhone = invoice.customer?.phone || invoice.customerPhone || 'N/A';
  const custAddress = invoice.customer?.address || invoice.customerAddress || 'Local Store';

  const subtotal = invoice.subtotal || 0;
  const taxAmount = invoice.taxAmount ?? invoice.tax ?? 0;
  const discountAmount = invoice.discountAmount ?? invoice.discounts ?? 0;
  const totalAmount = invoice.totalAmount || 0;
  const paidAmount = invoice.paidAmount || 0;
  const dueAmount = invoice.dueAmount || 0;
  const items = invoice.items || [];
  const cashier = invoice.staffName || invoice.staff || 'Staff';
  const isPaid = dueAmount <= 0;

  const formattedDate = invoice.timestamp 
    ? new Date(invoice.timestamp).toLocaleString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })
    : new Date().toLocaleString('en-IN');

  return (
    <div 
      className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-3 sm:p-5 animate-in fade-in duration-200 print:bg-transparent print:p-0 print:static print:block font-sans"
      onClick={(e) => e.stopPropagation()}
    >
      <div 
        className="bg-[#1F2937] border border-[#374151] rounded-2xl w-full max-w-4xl overflow-hidden shadow-2xl flex flex-col max-h-[92vh] print:max-h-none print:overflow-visible print:border-none print:shadow-none print:bg-white print:w-full print:block"
        onClick={(e) => e.stopPropagation()}
      >
        {/* 1. ADMIN HEADER (Read-Only ERP Style Header) */}
        <div className="p-4 border-b border-[#374151] bg-[#111827] flex flex-col sm:flex-row sm:items-center justify-between gap-3 print:hidden">
          <div className="space-y-1">
            <div className="flex items-center space-x-2">
              <FileText className="w-5 h-5 text-teal-400" />
              <h3 className="font-extrabold text-[#F3F4F6] text-base font-mono">Invoice Details</h3>
              <span className="text-[10px] bg-teal-500/10 text-teal-300 border border-teal-500/30 font-mono font-bold px-2 py-0.5 rounded">
                READ-ONLY PREVIEW
              </span>
            </div>
            <div className="flex flex-wrap items-center gap-3 text-xs font-mono text-slate-400">
              <span>Invoice #: <strong className="text-teal-300">{invoice.billNumber}</strong></span>
              <span>•</span>
              <span>Generated By: <strong className="text-slate-200">{cashier}</strong></span>
              <span>•</span>
              <span>Date: <strong className="text-slate-200">{formattedDate}</strong></span>
              <span>•</span>
              <span className="flex items-center gap-1">
                Status: {isPaid ? (
                  <span className="text-emerald-400 font-bold bg-emerald-500/10 border border-emerald-500/30 px-1.5 py-0.2 rounded text-[10px]">Paid</span>
                ) : (
                  <span className="text-amber-400 font-bold bg-amber-500/10 border border-amber-500/30 px-1.5 py-0.2 rounded text-[10px]">Dues Pending</span>
                )}
              </span>
            </div>
          </div>

          {/* Admin Action Buttons */}
          <div className="flex items-center space-x-2 shrink-0 self-end sm:self-auto font-mono">
            <button
              type="button"
              onClick={handleSendWhatsApp}
              className="flex items-center space-x-1.5 bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs px-3 py-2 rounded-xl transition shadow-sm"
              title="Send Invoice summary via WhatsApp"
            >
              <MessageSquare className="w-4 h-4" />
              <span>WhatsApp</span>
            </button>
            <button
              type="button"
              onClick={handlePrint}
              className="flex items-center space-x-1.5 bg-teal-600 hover:bg-teal-500 text-white font-bold text-xs px-3.5 py-2 rounded-xl transition shadow-sm"
            >
              <Printer className="w-4 h-4" />
              <span>Print Invoice</span>
            </button>
            <button
              type="button"
              onClick={handleDownloadPDF}
              className="flex items-center space-x-1.5 bg-[#273549] hover:bg-[#374151] text-slate-200 font-bold text-xs px-3.5 py-2 rounded-xl border border-[#374151] transition shadow-sm"
            >
              <Download className="w-4 h-4 text-teal-400" />
              <span>Download PDF</span>
            </button>
            <button
              type="button"
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-white rounded-xl hover:bg-[#374151] transition"
              title="Close Preview"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* 2. BODY CONTENT (Side-by-side Summary Panel & Thermal Receipt Preview) */}
        <div className="flex-1 overflow-y-auto p-4 grid grid-cols-1 lg:grid-cols-12 gap-4 font-mono">
          
          {/* LEFT: INVOICE SUMMARY PANEL (5 cols on Desktop) */}
          <div className="lg:col-span-5 bg-[#111827] border border-[#374151] rounded-xl p-4 space-y-4 flex flex-col justify-between print:hidden">
            <div className="space-y-3">
              <div className="border-b border-[#374151] pb-2 font-bold text-slate-200 text-xs flex items-center justify-between">
                <span>INVOICE SUMMARY</span>
                <ShieldCheck className="w-4 h-4 text-teal-400" />
              </div>

              <div className="space-y-2 text-xs">
                <div className="flex justify-between">
                  <span className="text-slate-400">Invoice Number</span>
                  <span className="font-bold text-teal-300">{invoice.billNumber}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">Customer</span>
                  <span className="font-bold text-slate-200">{custName}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-slate-400">Mobile Number</span>
                  <WhatsAppPhoneBadge phone={custPhone} showNumber={true} />
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">Payment Method</span>
                  <span className="font-bold text-teal-300 bg-teal-500/10 px-1.5 py-0.5 rounded border border-teal-500/20 text-[10px]">
                    {invoice.paymentMethod || 'CASH'}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">Generated By</span>
                  <span className="font-bold text-slate-200">{cashier}</span>
                </div>
              </div>

              <div className="border-t border-[#374151] pt-3 space-y-1.5 text-xs">
                <div className="flex justify-between">
                  <span className="text-slate-400">Subtotal</span>
                  <span className="font-bold text-slate-300">₹{formatNumberIN(subtotal)}</span>
                </div>
                {taxAmount > 0 && (
                  <div className="flex justify-between">
                    <span className="text-slate-400">GST</span>
                    <span className="font-bold text-slate-300">₹{formatNumberIN(taxAmount)}</span>
                  </div>
                )}
                {discountAmount > 0 && (
                  <div className="flex justify-between">
                    <span className="text-slate-400">Discount</span>
                    <span className="font-bold text-emerald-400">-₹{formatNumberIN(discountAmount)}</span>
                  </div>
                )}
                <div className="flex justify-between text-sm font-extrabold text-white pt-2 border-t border-[#374151]">
                  <span>Net Amount</span>
                  <span className="text-teal-400">₹{formatNumberIN(totalAmount)}</span>
                </div>
                <div className="flex justify-between text-xs pt-1">
                  <span className="text-slate-400">Amount Paid</span>
                  <span className="font-bold text-slate-200">₹{formatNumberIN(paidAmount)}</span>
                </div>
                <div className="flex justify-between text-xs">
                  <span className="text-slate-400">Balance Due</span>
                  <span className="font-bold text-amber-400">₹{formatNumberIN(dueAmount)}</span>
                </div>
              </div>
            </div>

            <div className="pt-3 border-t border-[#374151]">
              <div className={`p-2.5 rounded-xl border text-center text-xs font-bold ${
                isPaid 
                  ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400' 
                  : 'bg-amber-500/10 border-amber-500/30 text-amber-400'
              }`}>
                {isPaid ? '✓ PAYMENT COMPLETED IN FULL' : `⚠️ OUTSTANDING BALANCE: ₹${formatNumberIN(dueAmount)}`}
              </div>
            </div>
          </div>

          {/* RIGHT: READ-ONLY THERMAL RECEIPT PREVIEW (7 cols on Desktop) */}
          <div className="lg:col-span-7 flex justify-center bg-[#111827] p-4 rounded-xl border border-[#374151]">
            <div 
              className="p-4 bg-white text-black font-mono text-[11px] leading-tight w-full max-w-[80mm] shadow-lg rounded-sm print:p-0 print:shadow-none select-text" 
              id="admin-printable-receipt"
              style={{ fontFamily: "'Courier New', Courier, monospace" }}
            >
              {/* SHOP HEADER */}
              <div className="text-center pb-2 border-b border-black space-y-1">
                <div className="font-extrabold text-base tracking-tight uppercase">
                  {shopDetails?.shopName || 'VOLT ELECTRICALS'}
                </div>
                <div className="text-[11px] font-bold">
                  {shopDetails?.tagline || 'Power, Lighting & Hardware Store'}
                </div>
                <div className="text-[10px] whitespace-pre-line leading-tight">
                  {shopDetails?.address || 'Main Market Road,\nElectrical Substation,\nSector 4'}
                </div>
                <div className="text-[10px] pt-0.5 space-y-0.5">
                  <div>Phone : {shopDetails?.phone || '+91 9876543210'}</div>
                  <div>GSTIN : {shopDetails?.gstin || '07AAAAA0000A1Z5'}</div>
                </div>
              </div>

              {/* INVOICE META */}
              <div className="py-2 border-b border-black text-[11px] space-y-1">
                <div className="flex justify-between">
                  <span>Invoice No : <strong>{invoice.billNumber}</strong></span>
                  <span>Date : <strong>{invoice.timestamp ? new Date(invoice.timestamp).toLocaleDateString('en-GB') : new Date().toLocaleDateString('en-GB')}</strong></span>
                </div>
                <div className="flex justify-between">
                  <span>Cashier    : <strong>{cashier}</strong></span>
                  <span>Payment : <strong>{invoice.paymentMethod || 'Cash'}</strong></span>
                </div>
              </div>

              {/* CUSTOMER META */}
              <div className="py-2 border-b border-black text-[11px] space-y-1">
                <div>Customer : <strong>{custName}</strong></div>
                <div>Mobile   : <strong>{custPhone}</strong></div>
                <div>Address  : <strong>{custAddress}</strong></div>
              </div>

              {/* ITEMS TABLE */}
              <div className="py-2 border-b border-black">
                <table className="w-full text-[11px] border-collapse font-mono">
                  <thead>
                    <tr className="border-b border-black text-left">
                      <th className="py-1 text-left" style={{ width: '45%' }}>ITEM</th>
                      <th className="py-1 text-center" style={{ width: '12%' }}>QTY</th>
                      <th className="py-1 text-right" style={{ width: '21%' }}>RATE</th>
                      <th className="py-1 text-right" style={{ width: '22%' }}>TOTAL</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-300">
                    {items.map((item, idx) => {
                      const rate = item.unitPrice || item.basePrice || 0;
                      const lineTotal = item.total || (rate * item.qty);
                      return (
                        <tr key={idx} className="align-top">
                          <td className="py-1 pr-1 break-words font-medium">
                            {item.productName}
                          </td>
                          <td className="py-1 text-center font-bold">
                            {item.qty}
                          </td>
                          <td className="py-1 text-right whitespace-nowrap">
                            ₹{formatNumberIN(rate)}
                          </td>
                          <td className="py-1 text-right font-bold whitespace-nowrap">
                            ₹{formatNumberIN(lineTotal)}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>

              {/* TOTALS */}
              <div className="py-2 border-b border-black text-[11px] space-y-1 font-mono">
                <div className="flex justify-between">
                  <span>Subtotal</span>
                  <span>₹{formatNumberIN(subtotal)}</span>
                </div>

                {taxAmount > 0 && (
                  <div className="flex justify-between">
                    <span>GST ({shopDetails?.defaultTaxPercent || 18}%)</span>
                    <span>₹{formatNumberIN(taxAmount)}</span>
                  </div>
                )}

                {discountAmount > 0 && (
                  <div className="flex justify-between">
                    <span>Discount</span>
                    <span>-₹{formatNumberIN(discountAmount)}</span>
                  </div>
                )}

                <div className="border-t border-black pt-1 flex justify-between text-xs font-black">
                  <span>NET TOTAL</span>
                  <span>₹{formatNumberIN(totalAmount)}</span>
                </div>

                <div className="flex justify-between">
                  <span>Amount Paid</span>
                  <span>₹{formatNumberIN(paidAmount)}</span>
                </div>

                <div className="flex justify-between">
                  <span>Balance Due</span>
                  <span>₹{formatNumberIN(dueAmount)}</span>
                </div>

                <div className="pt-1 text-center">
                  {dueAmount <= 0 ? (
                    <div className="py-1 font-bold border border-black rounded text-center">
                      ✓ FULLY PAID
                    </div>
                  ) : (
                    <div className="py-1 font-bold border border-black rounded text-center">
                      Pending Due : ₹{formatNumberIN(dueAmount)}
                    </div>
                  )}
                </div>
              </div>

              {/* PAYMENT BREAKDOWN */}
              <div className="py-2 border-b border-black text-[11px] space-y-1 font-mono">
                <div className="flex justify-between">
                  <span>Payment Mode :</span>
                  <strong>{invoice.paymentMethod || 'Cash'}</strong>
                </div>
              </div>

              {/* FOOTER & BARCODE */}
              <div className="pt-2 text-center font-mono space-y-1.5">
                <div className="text-[11px] font-bold">Thank you for shopping with us!</div>
                <div className="text-[10px]">Goods once sold cannot be returned.</div>
                <div className="text-[11px] font-bold">Visit Again</div>

                <div className="pt-2">
                  <div className="text-xs tracking-widest font-bold">
                    ||| |||| ||||| || |||||| | ||||| |||| ||
                  </div>
                  <div className="text-[10px] font-bold mt-0.5">
                    {invoice.billNumber}
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>

        {/* 3. ADMIN ACTION FOOTER */}
        <div className="p-4 border-t border-[#374151] bg-[#111827] flex items-center justify-between print:hidden font-mono text-xs">
          <div className="text-slate-400">
            System Record ID: <span className="text-slate-200">{invoice.id || invoice.billNumber}</span>
          </div>
          <div className="flex items-center space-x-2">
            <button
              type="button"
              onClick={handlePrint}
              className="px-4 py-2 bg-teal-600 hover:bg-teal-500 text-white font-bold rounded-xl transition flex items-center space-x-1.5"
            >
              <Printer className="w-4 h-4" />
              <span>Print Invoice</span>
            </button>
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 bg-[#273549] hover:bg-[#374151] text-slate-300 font-bold rounded-xl border border-[#374151] transition"
            >
              Close
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
